# Generated by Django 5.2 on 2025-04-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('cgpa', models.FloatField()),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
            ],
        ),
    ]
