# Generated by Django 5.2 on 2025-04-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_deadline_job_application_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='application_deadline',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='eligibility_criteria',
            new_name='eligibility',
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
