# Generated by Django 5.2 on 2025-04-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='preferred_location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(default=1, upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
