# Generated by Django 5.2 on 2025-04-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jobapplication_status_alter_jobapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
