# Generated by Django 5.2.7 on 2025-10-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_jobapplication_preferred_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminotp',
            name='otp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
